// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gs-open-provider/op-auth-admin-gateway/models"
)

// RefreshTokenOKCode is the HTTP code returned for type RefreshTokenOK
const RefreshTokenOKCode int = 200

/*RefreshTokenOK OK

swagger:response refreshTokenOK
*/
type RefreshTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewRefreshTokenOK creates RefreshTokenOK with default headers values
func NewRefreshTokenOK() *RefreshTokenOK {

	return &RefreshTokenOK{}
}

// WithPayload adds the payload to the refresh token o k response
func (o *RefreshTokenOK) WithPayload(payload *models.LoginResponse) *RefreshTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token o k response
func (o *RefreshTokenOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenBadRequestCode is the HTTP code returned for type RefreshTokenBadRequest
const RefreshTokenBadRequestCode int = 400

/*RefreshTokenBadRequest BAD REQUEST

swagger:response refreshTokenBadRequest
*/
type RefreshTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewRefreshTokenBadRequest creates RefreshTokenBadRequest with default headers values
func NewRefreshTokenBadRequest() *RefreshTokenBadRequest {

	return &RefreshTokenBadRequest{}
}

// WithPayload adds the payload to the refresh token bad request response
func (o *RefreshTokenBadRequest) WithPayload(payload *models.GeneralResponse) *RefreshTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token bad request response
func (o *RefreshTokenBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenUnauthorizedCode is the HTTP code returned for type RefreshTokenUnauthorized
const RefreshTokenUnauthorizedCode int = 401

/*RefreshTokenUnauthorized UNAUTHORIZED

swagger:response refreshTokenUnauthorized
*/
type RefreshTokenUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewRefreshTokenUnauthorized creates RefreshTokenUnauthorized with default headers values
func NewRefreshTokenUnauthorized() *RefreshTokenUnauthorized {

	return &RefreshTokenUnauthorized{}
}

// WithPayload adds the payload to the refresh token unauthorized response
func (o *RefreshTokenUnauthorized) WithPayload(payload *models.GeneralResponse) *RefreshTokenUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token unauthorized response
func (o *RefreshTokenUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenForbiddenCode is the HTTP code returned for type RefreshTokenForbidden
const RefreshTokenForbiddenCode int = 403

/*RefreshTokenForbidden FORBIDDEN

swagger:response refreshTokenForbidden
*/
type RefreshTokenForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewRefreshTokenForbidden creates RefreshTokenForbidden with default headers values
func NewRefreshTokenForbidden() *RefreshTokenForbidden {

	return &RefreshTokenForbidden{}
}

// WithPayload adds the payload to the refresh token forbidden response
func (o *RefreshTokenForbidden) WithPayload(payload *models.GeneralResponse) *RefreshTokenForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token forbidden response
func (o *RefreshTokenForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenNotFoundCode is the HTTP code returned for type RefreshTokenNotFound
const RefreshTokenNotFoundCode int = 404

/*RefreshTokenNotFound NOT FOUND

swagger:response refreshTokenNotFound
*/
type RefreshTokenNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewRefreshTokenNotFound creates RefreshTokenNotFound with default headers values
func NewRefreshTokenNotFound() *RefreshTokenNotFound {

	return &RefreshTokenNotFound{}
}

// WithPayload adds the payload to the refresh token not found response
func (o *RefreshTokenNotFound) WithPayload(payload *models.GeneralResponse) *RefreshTokenNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token not found response
func (o *RefreshTokenNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenInternalServerErrorCode is the HTTP code returned for type RefreshTokenInternalServerError
const RefreshTokenInternalServerErrorCode int = 500

/*RefreshTokenInternalServerError INTERNAL SERVER ERROR

swagger:response refreshTokenInternalServerError
*/
type RefreshTokenInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewRefreshTokenInternalServerError creates RefreshTokenInternalServerError with default headers values
func NewRefreshTokenInternalServerError() *RefreshTokenInternalServerError {

	return &RefreshTokenInternalServerError{}
}

// WithPayload adds the payload to the refresh token internal server error response
func (o *RefreshTokenInternalServerError) WithPayload(payload *models.GeneralResponse) *RefreshTokenInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token internal server error response
func (o *RefreshTokenInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
