// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/gs-open-provider/op-auth-admin-gateway/models"
)

// NewRegisterUserDetailsParams creates a new RegisterUserDetailsParams object
// no default values defined in spec.
func NewRegisterUserDetailsParams() RegisterUserDetailsParams {

	return RegisterUserDetailsParams{}
}

// RegisterUserDetailsParams contains all the bound params for the register user details operation
// typically these are obtained from a http.Request
//
// swagger:parameters RegisterUserDetails
type RegisterUserDetailsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	RegisterRequest *models.RegisterDetailsRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRegisterUserDetailsParams() beforehand.
func (o *RegisterUserDetailsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RegisterDetailsRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("registerRequest", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RegisterRequest = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
