// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/gs-open-provider/op-auth-admin-gateway/restapi/operations/auth"
)

// NewAuthServiceAPI creates a new AuthService instance
func NewAuthServiceAPI(spec *loads.Document) *AuthServiceAPI {
	return &AuthServiceAPI{
		handlers:                        make(map[string]map[string]http.Handler),
		formats:                         strfmt.Default,
		defaultConsumes:                 "application/json",
		defaultProduces:                 "application/json",
		customConsumers:                 make(map[string]runtime.Consumer),
		customProducers:                 make(map[string]runtime.Producer),
		ServerShutdown:                  func() {},
		spec:                            spec,
		ServeError:                      errors.ServeError,
		BasicAuthenticator:              security.BasicAuth,
		APIKeyAuthenticator:             security.APIKeyAuth,
		BearerAuthenticator:             security.BearerAuth,
		JSONConsumer:                    runtime.JSONConsumer(),
		JSONProducer:                    runtime.JSONProducer(),
		GetHandler:                      nil,
		AuthRegisterUserHandler:         nil,
		AuthRegisterCalbackHandler:      nil,
		AuthRegisterConfirmationHandler: nil,
		AuthRegisterUserDetailsHandler:  nil,
		AuthLoginUserHandler:            nil,
		AuthLoginCallbackHandler:        nil,
		AuthRefreshTokenHandler:         nil,
	}
}

/*AuthServiceAPI Authentication Service API */
type AuthServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// GetHandler sets the operation handler for the get operation
	GetHandler GetHandler
	// AuthLoginCallbackHandler sets the operation handler for the login callback operation
	AuthLoginCallbackHandler auth.LoginCallbackHandler
	// AuthLoginUserHandler sets the operation handler for the login user operation
	AuthLoginUserHandler auth.LoginUserHandler
	// AuthRefreshTokenHandler sets the operation handler for the refresh token operation
	AuthRefreshTokenHandler auth.RefreshTokenHandler
	// AuthRegisterCalbackHandler sets the operation handler for the register calback operation
	AuthRegisterCalbackHandler auth.RegisterCalbackHandler
	// AuthRegisterConfirmationHandler sets the operation handler for the register confirmation operation
	AuthRegisterConfirmationHandler auth.RegisterConfirmationHandler
	// AuthRegisterUserHandler sets the operation handler for the register user operation
	AuthRegisterUserHandler auth.RegisterUserHandler
	// AuthRegisterUserDetailsHandler sets the operation handler for the register user details operation
	AuthRegisterUserDetailsHandler auth.RegisterUserDetailsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *AuthServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *AuthServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *AuthServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *AuthServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *AuthServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *AuthServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *AuthServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the AuthServiceAPI
func (o *AuthServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetHandler == nil {
		unregistered = append(unregistered, "GetHandler")
	}

	if o.AuthLoginCallbackHandler == nil {
		unregistered = append(unregistered, "auth.LoginCallbackHandler")
	}

	if o.AuthLoginUserHandler == nil {
		unregistered = append(unregistered, "auth.LoginUserHandler")
	}

	if o.AuthRefreshTokenHandler == nil {
		unregistered = append(unregistered, "auth.RefreshTokenHandler")
	}

	if o.AuthRegisterCalbackHandler == nil {
		unregistered = append(unregistered, "auth.RegisterCalbackHandler")
	}

	if o.AuthRegisterConfirmationHandler == nil {
		unregistered = append(unregistered, "auth.RegisterConfirmationHandler")
	}

	if o.AuthRegisterUserHandler == nil {
		unregistered = append(unregistered, "auth.RegisterUserHandler")
	}

	if o.AuthRegisterUserDetailsHandler == nil {
		unregistered = append(unregistered, "auth.RegisterUserDetailsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *AuthServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *AuthServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *AuthServiceAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *AuthServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *AuthServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *AuthServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the auth service API
func (o *AuthServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *AuthServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = NewGet(o.context, o.GetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/oauth2/oauth-signin-cb"] = auth.NewLoginCallback(o.context, o.AuthLoginCallbackHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/signin"] = auth.NewLoginUser(o.context, o.AuthLoginUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/auth/refresh-token"] = auth.NewRefreshToken(o.context, o.AuthRefreshTokenHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/oauth2/oauth-signup-cb"] = auth.NewRegisterCalback(o.context, o.AuthRegisterCalbackHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/auth/email-confirmation/{token}"] = auth.NewRegisterConfirmation(o.context, o.AuthRegisterConfirmationHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/signup"] = auth.NewRegisterUser(o.context, o.AuthRegisterUserHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/user-details"] = auth.NewRegisterUserDetails(o.context, o.AuthRegisterUserDetailsHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *AuthServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *AuthServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *AuthServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *AuthServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
