swagger: '2.0'
info:
  title: Auth Service
  description: Authentication Service API
  contact:
    name: NEWS API Support
  version: 1.0.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    $ref: ./paths/default.yml
  /v1/auth/signup:
    $ref: ./paths/auth/register.yml
  /v1/auth/user-details:
    $ref: ./paths/auth/registerDetails.yml
  /v1/auth/email-confirmation/{token}:
    $ref: ./paths/auth/registerConfirmation.yml
  /v1/auth/signin:
    $ref: ./paths/auth/login.yml
  /v1/auth/refresh-token:
    $ref: ./paths/auth/refreshToken.yml
  /v1/oauth2/oauth-signup-cb:
    $ref: ./paths/auth/callbackRegister.yml
  /v1/oauth2/oauth-signin-cb:
    $ref: ./paths/auth/callbackLogin.yml
definitions:
  generalResponse:
    $ref: ./definitions/generalResponse.yml